version: "3.9"

volumes:
  tfgvolume:
    name: tfg-volume

networks:
  tfgnetwork:
    name: tfg-network

services:
  pg:
    image: postgres:12.0
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - tfgvolume:/var/lib/postgresql/data
      - ./scripts/db:/docker-entrypoint-initdb.d/
    networks:
      - tfgnetwork
  tfg_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_PORT: ${API_PORT}
    env_file:
      - .env
    depends_on:
      - pg
    volumes:
      - ./:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - tfgnetwork
    env_file:
      - .env
    entrypoint: ["/bin/bash", "./scripts/entrypoint.sh"]
